### ISSUE TITLE
Incompatible with pydantic 1.10.15

### ISSUE THREAD

**Issue by Lintonash** [argoproj-labs/hera#1021]
<h2>Pre-bug-report checklist</h2>

**1. This bug can be reproduced using pure Argo YAML**
- [ ] Yes [👉 Please report a bug to the Argo Workflows GitHub 👈](https://github.com/argoproj/argo-workflows/issues/new/choose)
- [x ] No

_If yes, it is more likely to be an Argo bug unrelated to Hera. Please double check before submitting an issue to Hera._

**2. This bug occurs in Hera when...**
- [ ] exporting to YAML
- [ ] submitting to Argo
- [ ] running on Argo with the Hera runner
- [x ] other: 

<h2>Bug report</h2>

**Describe the bug**
When using:
-python 3.11.6
-pydantic 1.10.15 (latest pydantic v1)
-hera 5.14.3

running
```py
from hera.workflows import Workflow
```
gives the error below

_Error log if applicable_:
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[3], line 1
----> 1 from hera.workflows import Workflow

File /usr/local/lib/python3.11/site-packages/hera/workflows/__init__.py:33
     31 from hera.workflows.exceptions import InvalidDispatchType, InvalidTemplateCall, InvalidType
     32 from hera.workflows.http_template import HTTP
---> 33 from hera.workflows.io import RunnerInput, RunnerOutput
     34 from hera.workflows.metrics import Counter, Gauge, Histogram, Label, Metric, Metrics
     35 from hera.workflows.operator import Operator

File /usr/local/lib/python3.11/site-packages/hera/workflows/io/__init__.py:6
      3 from importlib.util import find_spec
      5 if find_spec("pydantic.v1"):
----> 6     from hera.workflows.io.v2 import RunnerInput, RunnerOutput
      7 else:
      8     from hera.workflows.io.v1 import RunnerInput, RunnerOutput  # type: ignore

File /usr/local/lib/python3.11/site-packages/hera/workflows/io/v2.py:27
     25 if find_spec("pydantic.v1"):
     26     from pydantic import BaseModel
---> 27     from pydantic_core import PydanticUndefined
     29     class RunnerInput(BaseModel):
     30         """Input model usable by the Hera Runner.
     31 
     32         RunnerInput is a Pydantic model which users can create a subclass of. When a subclass
   (...)
     35         for the script_pydantic_io experimental feature.
     36         """

ModuleNotFoundError: No module named 'pydantic_core'
```

**To Reproduce**
Full Hera code to reproduce the bug:
```py
from hera.workflows import Workflow
```

**Expected behavior**
_should be able to import._

**Environment**
- Hera Version: 5.14.3
- Python Version: 3.11.6
- Pydantic Version: 1.10.15 (latest v1)

**Additional context**
`pydantic 1.10.14` doesn't have the problem possibly because `findspec("pydantic.v1")` returns `None` for some reason while  `findspec` has a return value for `pydantic 1.10.15`.

**Comment by elliotgunton** [comment]
Incidentally this is the reason our CI checks have suddenly started failing for pydantic v1. We install `poetry run pip install "pydantic<2"` which wasn't expected to change again until https://github.com/pydantic/pydantic/pull/9042

**Comment by exs-dmiketa** [comment]
Hi, I added the `pydantic.v1` namespace to `pydantic==1.10.15` and effectively broke your code. I'll briefly explain the motivation for the change and how you can fix this issue on your end.

Before this PR it was a bit tricky to write Pydantic code which is compatible with both v1 and v2 while robustly satisfying type checkers and linters. As a result some extended codebases had to pin Pydantic to v1. With the introduction of `pydantic.v1` inside `pydantic==1.10.15` one can write `from pydantic.v1 import ...` and it'll work in both versions. Migrate your entire v1 codebase to this style and you will be able to release the version pin. Now compatible with `pydantic>=2`, you can organically migrate v1-style code to v2-style in your own time.

Now onto your issue. Instead of checking for the existence of `pydantic.v1` - which is no longer a differentiator of versions - check the value of `pydantic.VERSION` instead.
