### ISSUE TITLE
Consider versioned documentation

### ISSUE THREAD

**Issue by abschm** [argoproj-labs/hera#746]
**Is your feature request related to a problem? Please describe.**
I was looking for versioned documentation and noticed it technically exists but is a little underutilized right now:

![image](https://github.com/argoproj-labs/hera/assets/36536963/fc08d254-096d-4b52-834d-c9e6e002ab7d)

This makes sense since the documentation is new, but eventually making the documentation versioned would be helpful for users.

**Comment by samj1912** [comment]
The docs are already versioned. You should be able to see the documentation for a specific version using

https://hera.readthedocs.io/en/$version_num


For eg 

https://hera.readthedocs.io/en/5.5.2/

Note, this is only available from v5 onwards.

**Comment by abschm** [comment]
In my opinion, the issue still stands - there is no way to know about/navigate to the versioned documentation, and the black panel I screenshotted is out of date/irrelevant, so for users, the versioned documentation might as well not exist.

**Comment by adrvolan** [comment]
All of the versions are accessible with a direct URL, but for some reason most of them are marked as hidden and do not show on the flyout menu.

Is there a way on your side to list them again? I think it's an admin thing to do rather than code change. It properly reads the tags, just hides them.

The hidden versions are listed in [robots.txt](https://hera.readthedocs.io/robots.txt))

**Comment by flaviuvadan** [comment]
This shows up when the Hera docs load. The version dropdown shows on local via `mkdocs serve`
![Screenshot 2023-08-14 at 10 25 15 AM](https://github.com/argoproj-labs/hera/assets/18152652/fd96e400-75e0-4c14-8fc5-a6e096b38f5f)

**Comment by samj1912** [comment]
Updated rtd automation rules. Versions should be public now.
