### ISSUE TITLE
Documentation link is broken

### ISSUE THREAD

**Issue by vikramsg** [argoproj-labs/hera#779]
This is not urgent but the documentation link for authentication is broken here.
https://github.com/argoproj-labs/hera/blob/bb3c7c0009b6ed604467901f1fee9883eb825c2d/README.md?plain=1#L116

**Comment by elliotgunton** [comment]
This is because the README is reused for the docs website (the link works from https://hera.readthedocs.io/en/stable/) - we can update to the full (stable) link `https://hera.readthedocs.io/en/stable/walk-through/authentication/` or change to a purpose-built home page for the docs website and tailor the README for the repo itself.
